name: Docker Test

on: 
  workflow_call:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: docker build --target test ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
      - run: docker cp ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test:/project/coverage ./coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
