name: Typescript CI

on: 
  workflow_call:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      
  ts-lint:
    uses: organisation72/workflows/.github/workflows/typescript/lint.yml@main

#   test:
#     needs: lint
#     runs-on: ubuntu-latest
    
#     strategy:
#       matrix:
#         node-version: [16.x, 18.x, 20.x]

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: yarn install --frozen-lockfile
#       - run: yarn test
    
#   build:
#     needs: test
#     runs-on: ubuntu-latest
    
#     strategy:
#       matrix:
#         node-version: [16.x, 18.x, 20.x]

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: yarn install --frozen-lockfile
#       - run: yarn build

  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
