name: Typescript CI

on: 
  workflow_call:
  workflow_dispatch:
  
jobs:
#   lint:
#     uses: organisation72/workflows/.github/workflows/typescript-lint.yml@main
    
#   build:
#     needs: lint
#     uses: organisation72/workflows/.github/workflows/typescript-build.yml@main
    
#   test:
#     needs: build
#     uses: organisation72/workflows/.github/workflows/typescript-test.yml@main

#   build-and-push-image:
#     needs: test
#     uses: organisation72/workflows/.github/workflows/build-and-push-image.yml@main

#   docker-build:
#     needs: lint
#     uses: organisation72/workflows/.github/workflows/docker-build.yml@main

#   docker-compose-test:
#     needs: lint
    uses: organisation72/workflows/.github/workflows/docker-compose-test.yml@main
