name: Typescript CI

on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
  
jobs:
  lint:
    uses: organisation72/workflows/.github/workflows/typescript-lint.yml@main

  test:
    needs: lint
    uses: organisation72/workflows/.github/workflows/docker-compose-test.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  build-and-push-image:
    needs: test
    uses: organisation72/workflows/.github/workflows/build-and-push-image.yml@main

  deployment:
    needs: build-and-push-image
    uses: organisation72/workflows/.github/workflows/deploy-pr.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}