name: Typescript CI

on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true
  
jobs:
  lint:
    uses: organisation72/workflows/.github/workflows/typescript-lint.yml@main

  test:
    needs: lint
    uses: organisation72/workflows/.github/workflows/docker-compose-test.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  build-and-push-image:
    needs: test
    uses: organisation72/workflows/.github/workflows/build-and-push-image.yml@main
